# Configuration for repository issue template syncing
# ref: https://github.com/BetaHuhn/repo-file-sync-action
group:
  # files shared across all repositories
  - files:
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
        exclude: |
          bug-report.yml
          bug-report-nebari.yml
      - source: .github/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
      - source: LICENSE
        dest: LICENSE
      - source: CONTRIBUTING.md
        dest: CONTRIBUTING.md
    repos: |
      nebari-dev/nebari
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-jupyterhub-theme
  # finer grained bug report issues - Nebari
  - files:
      - source: .github/ISSUE_TEMPLATE/bug-report-nebari.yml
      - dest: .github/ISSUE_TEMPLATE/bug-report.yml
    repos: |
      nebari-dev/nebari
  # general bug report
  - files:
      - source: .github/ISSUE_TEMPLATE/bug-report.yml
      - dest: .github/ISSUE_TEMPLATE/bug-report.yml
    repos: |
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-jupyterhub-theme
