# Configuration for repository issue template syncing
# ref: https://github.com/BetaHuhn/repo-file-sync-action
group:
  # files shared across all repositories
  - files:
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
        exclude: |
          bug-report.yml
          bug-report-nebari.yml
          RFD.md
          config-docs-repo.yml
          documentation.yml
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: CONTRIBUTING.md
        dest: CONTRIBUTING.md
    repos: |
      nebari-dev/nebari
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-jupyterhub-theme
      nebari-dev/nebari-deploy
      nebari-dev/nebari-demo

  # finer grained bug report issues - Nebari
  - files:
      - source: .github/ISSUE_TEMPLATE/bug-report-nebari.yml
        dest: .github/ISSUE_TEMPLATE/bug-report.yml
        deleteOrphaned: true
    repos: |
      nebari-dev/nebari

  # general bug report
  - files:
      - source: .github/ISSUE_TEMPLATE/bug-report.yml
        dest: .github/ISSUE_TEMPLATE/bug-report.yml
        deleteOrphaned: true
    repos: |
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-jupyterhub-theme
      nebari-dev/nebari-deploy
      nebari-dev/nebari-demo

  # pull request template - adds the documentation section
  - files:
      - source: .github/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
        deleteOrphaned: true
    repos: |
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-jupyterhub-theme
      nebari-dev/nebari-deploy
      nebari-dev/nebari-demo

  # pull request template - without the documentation section
  - files:
      - source: .github/PULL_REQUEST_TEMPLATE_simple.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
        deleteOrphaned: true
    repos: |
      nebari-dev/nebari

  # RFD - should only be in the governance repo
  - files:
      - source: .github/ISSUE_TEMPLATE/RFD.md
        dest: .github/ISSUE_TEMPLATE/RFD.md
        deleteOrphaned: true
    repos: |
      nebari-dev/governance

  # nebari-docs config
  - files:
      - source: .github/ISSUE_TEMPLATE/config-docs.yml
        dest: .github/ISSUE_TEMPLATE/config.yml
      - source: .github/ISSUE_TEMPLATE/documentation.yml
        dest: .github/ISSUE_TEMPLATE/documentation.yml
        deleteOrphaned: true
    repos: |
      nebari-dev/nebari-docs
      nebari-dev/docker-images
      nebari-dev/governance
      nebari-dev/nebari-demo
      nebari-dev/nebari-deploy
      nebari-dev/nebari-jupyterhub-theme
