# Configuration for repository issue template syncing
# ref: https://github.com/BetaHuhn/repo-file-sync-action
group:
  # Our public repositories use a YML file
  - repos: |
      nebari-dev/nebari
      nebari-dev/docker-images
      nebari-dev/governance
    files:
      - source: .github/ISSUE_TEMPLATE/
        dest: .github/ISSUE_TEMPLATE/
      - source: LICENSE
        dest: LICENSE
