name: Sync Issue Templates
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-issue-templates:
    name: Sync Issue templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🛎
        uses: actions/checkout@v3

      - name: Run GitHub File Sync ♻️
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          BRANCH_PREFIX: github
          COMMIT_BODY: "MAINT - Sync .github files :robot:"
          PR_LABELS: |
            "type: file sync ♻️"
